name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
        pip install pytest pytest-mock pytest-asyncio pytest-cov mongomock
    
    - name: Create .env file
      run: |
        echo "MONGODB_URI=mongodb://localhost:27017/dontrade_test" > backend/.env
        echo "JWT_SECRET=test_secret_key_for_github_actions" >> backend/.env
        echo "IBKR_ACCOUNT=test_account" >> backend/.env
        echo "TESTING=True" >> backend/.env
    
    - name: Run tests with pytest
      run: |
        cd backend
        python -m pytest \
          test/test_consecutive_analysis.py \
          test/test_yfinance_direct.py \
          test/test_yfinance_sync.py \
          test/test_hurst_exponent.py \
          test/test_next_day_stats.py \
          test/test_volatility.py \
          test/test_data_utils.py \
          test/test_probability_distribution.py \
          -v --cov=app
    
    - name: Generate coverage report
      run: |
        cd backend
        python -m pytest \
          test/test_consecutive_analysis.py \
          test/test_yfinance_direct.py \
          test/test_yfinance_sync.py \
          test/test_hurst_exponent.py \
          test/test_next_day_stats.py \
          test/test_volatility.py \
          test/test_data_utils.py \
          test/test_probability_distribution.py \
          --cov=app --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./backend/coverage.xml
        fail_ci_if_error: false 